const Data = [
    {
      saleBadge: false,
      img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
      title: "Fancy Product",
      reviews: false,
      strike: false,
      price1: "40.00",
      price2: "80.00",
      cartButton: "View Options",
    },
    {
      saleBadge: true,
      img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
      title: "Special Item",
      reviews: true,
      strike: true,
      price1: "20.00",
      price2: "18.00",
      cartButton: "Add to cart",
    },
    {
      saleBadge: true,
      img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
      title: "Sale Item",
      reviews: false,
      strike: true,
      price1: "50.00",
      price2: "25.00",
      cartButton: "Add to cart",
    },
    {
      saleBadge: false,
      img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
      title: "Popular Item",
      strike: false,
      reviews: true,
      price1: "0",
      price2: "40.00",
      cartButton: "Add to cart",
    },
    {
      saleBadge: true,
      img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
      title: "Sale Item",
      reviews: false,
      strike: false,
      price1: "50.00",
      price2: "25.00",
      cartButton: "Add to cart",
    },
    {
      saleBadge: false,
      img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
      title: "Fancy Product",
      strike: false,
      reviews: false,
      price1: "120.00",
      price2: "280.00",
      cartButton: "View Options",
    },
    {
      saleBadge: true,
      img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
      title: "Special Item",
      reviews: true,
      strike: true,
      price1: "20.00",
      price2: "18.00",
      cartButton: "Add to cart",
    },
    {
      saleBadge: false,
      img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
      title: "Popular Item",
      strike: false,
      reviews: true,
      price1: "0",
      price2: "40.00",
      cartButton: "Add to cart",
    },
  ];
  
  export default Data;